# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2244bfc52d3a9d538d9d232c7e714a4c747af9434700e254eb395b9531821d4086f3b969691b35289e4062f80e5282f2741ddecb6b6d571aad32ededa21059df

test:
  secret_key_base: ce7df6c0c5f7b091aaa22620e6db07cc284d5524475e6319c9c1ed05faa85fb5add7f10888199f42d75b5ebd4eb18394ed669f9e70207324ad63fa1d07844339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
